/**
 * @fileoverview useTheme Hook — Route-based theme resolution for the public site.
 *
 * Provides the current ThemeConfig based on the active route. Reads from the
 * static `themes.ts` config (generated by the admin publish pipeline) — zero
 * runtime database calls, making it fully SSG-compatible.
 *
 * ## Architecture
 * The theme system has two layers:
 * 1. **Admin layer** (site_themes table → Themes.tsx page → publish pipeline)
 *    writes static config to `src/config/themes.ts`.
 * 2. **Runtime layer** (this hook + `applyThemeToRoot()`) reads that static config
 *    and resolves CSS variables at page load.
 *
 * ## Route Resolution
 * 1. Extract top-level path segment from current pathname.
 * 2. Check `routeThemeMappings` for a route-specific theme override.
 * 3. Fall back to `activeTheme` (the default published theme).
 *
 * ## Exports
 * - **useTheme()**: Route-aware hook returning { theme, accentHsl, isDefaultTheme }.
 * - **useActiveTheme()**: Returns the default theme without route context —
 *   useful in SSG contexts where `useLocation` isn't available.
 *
 * ## Data Contract
 * - Depends on: `src/config/themes.ts` (activeTheme, routeThemeMappings, publishedThemes).
 * - No Supabase/DB imports. No secrets. No authentication.
 *
 * ## SSG Compatibility
 * - Fully SSG-safe. Theme is determined at build time for static routes.
 *   `useLocation` is provided by react-router-dom's SSG adapter.
 *
 * ## Portability
 * - Copy this hook + `src/config/themes.ts`. The theme config file must export
 *   `activeTheme`, `getThemeForRoute`, and the `ThemeConfig` type.
 */

import { useMemo } from 'react';
import { useLocation } from 'react-router-dom';
import { 
  activeTheme, 
  getThemeForRoute, 
  type ThemeConfig 
} from '@/config/themes';

/**
 * Return type for useTheme hook
 * @interface UseThemeResult
 */
interface UseThemeResult {
  /** Current theme configuration object */
  theme: ThemeConfig;
  /** Accent color in HSL format (e.g., "240 70% 60%") */
  accentHsl: string;
  /** Whether current theme is the default/active theme */
  isDefaultTheme: boolean;
}

/**
 * useTheme - Get current theme based on route
 * 
 * SSG-safe hook that reads from static config (themes.ts).
 * No database calls - theme is determined at build time.
 * 
 * Theme selection logic:
 * 1. Check routeThemeMappings for route-specific theme
 * 2. Fall back to activeTheme (default)
 * 
 * @hook
 * @example
 * const { theme, accentHsl, isDefaultTheme } = useTheme();
 * 
 * // Use theme config
 * <div style={{ color: `hsl(${accentHsl})` }}>
 *   Themed content
 * </div>
 * 
 * @returns {UseThemeResult} Theme configuration and helpers
 */
export function useTheme(): UseThemeResult {
  const location = useLocation();
  
  /**
   * Get theme for current route (memoized)
   */
  const theme = useMemo(() => {
    return getThemeForRoute(location.pathname);
  }, [location.pathname]);
  
  /**
   * Compute HSL string for accent color (memoized)
   */
  const accentHsl = useMemo(() => {
    const { h, s, l } = theme.accentConfig;
    return `${h} ${s}% ${l}%`;
  }, [theme]);
  
  const isDefaultTheme = theme.id === activeTheme.id;
  
  return {
    theme,
    accentHsl,
    isDefaultTheme,
  };
}

/**
 * useActiveTheme - Get the active (default) theme without route context
 * 
 * Useful for SSG where route context may not be available,
 * or when you explicitly want the default theme regardless of route.
 * 
 * @hook
 * @example
 * // In a context where useLocation isn't available
 * const theme = useActiveTheme();
 * 
 * @returns {ThemeConfig} The active/default theme configuration
 */
export function useActiveTheme(): ThemeConfig {
  return activeTheme;
}
