/**
 * Static Theme Configuration
 * 
 * This file is the PRODUCTION source of truth for themes.
 * Generated by admin "Publish to Production" workflow.
 * 
 * DO NOT edit manually - use admin theme editor and "Publish to Production".
 * 
 * SSG Compatible: Imported statically, zero runtime DB calls.
 * 
 * @generated 2026-01-16
 */

// Logo element types for embedded config
export interface LogoElementConfig {
  size: number;
  weight: number;
  solidColor: string;
  useGradient: boolean;
  gradientFrom: string;
  gradientTo: string;
  gradientAngle: number;
  marginLeft: number;
  marginRight: number;
  verticalOffset?: number;
}

export interface StreakElementConfig {
  length: number;
  leftThick: number;
  rightThick: number;
  solidColor: string;
  useGradient: boolean;
  gradientFrom: string;
  gradientTo: string;
  gradientAngle: number;
  marginLeft: number;
  marginRight: number;
}

export interface TaglineElementConfig {
  size: number;
  weight: number;
  solidColor: string;
  useGradient: boolean;
  gradientFrom: string;
  gradientTo: string;
  gradientAngle: number;
  marginLeft: number;
  marginRight: number;
  marginTop: number;
}

export interface ThemeConfig {
  id: string;
  name: string;
  baseHue: number;
  accentConfig: {
    accent: string;
    accentHover: string;
    accentGlow: string;
    accentForeground: string;
    h: number;
    s: number;
    l: number;
  };
  staticColors: {
    background: string;
    foreground: string;
    card: string;
    cardForeground: string;
    popover: string;
    popoverForeground: string;
    primary: string;
    primaryLight: string;
    primaryForeground: string;
    secondary: string;
    secondaryForeground: string;
    muted: string;
    mutedForeground: string;
    border: string;
    input: string;
    ring: string;
  };
  gradientConfigs: {
    hero: string;
    cta: string;
    text: string;
  };
  logoVersionId?: string;
  logoConfig?: {
    taglineText: string;
    everConfig: LogoElementConfig;
    intentConfig: LogoElementConfig;
    streakConfig: StreakElementConfig;
    taglineConfig: TaglineElementConfig;
  };
}

export interface RouteThemeMapping {
  route: string;
  themeId: string;
}

// ============================================
// ACTIVE PRODUCTION THEME (Luxury Gold)
// ============================================
export const activeTheme: ThemeConfig = {
  id: 'luxury-gold',
  name: 'Luxury Gold',
  baseHue: 38,
  accentConfig: {
    accent: '38 92% 50%',
    accentHover: '38 95% 45%',
    accentGlow: '38 95% 60%',
    accentForeground: '0 0% 5%',
    h: 38,
    s: 92,
    l: 50,
  },
  staticColors: {
    background: '0 0% 5%',
    foreground: '40 10% 91%',
    card: '0 0% 8%',
    cardForeground: '40 10% 91%',
    popover: '0 0% 8%',
    popoverForeground: '40 10% 91%',
    primary: '0 0% 12%',
    primaryLight: '0 0% 18%',
    primaryForeground: '40 10% 91%',
    secondary: '0 0% 10%',
    secondaryForeground: '40 10% 91%',
    muted: '0 0% 14%',
    mutedForeground: '220 10% 55%',
    border: '0 0% 16%',
    input: '0 0% 16%',
    ring: '38 92% 50%',
  },
  gradientConfigs: {
    hero: 'linear-gradient(180deg, hsl(0 0% 5%) 0%, hsl(0 0% 7%) 50%, hsl(0 0% 5%) 100%)',
    cta: 'linear-gradient(135deg, hsl(38 92% 50%) 0%, hsl(38 95% 45%) 100%)',
    text: 'linear-gradient(135deg, hsl(38 92% 50%) 0%, hsl(42 95% 60%) 50%, hsl(38 92% 50%) 100%)',
  },
  logoVersionId: 'f427aa31-0016-408e-98d4-86a7573b1b15',
  logoConfig: {
    taglineText: 'Web Design & Practical AI',
    everConfig: {
        "size": 72,
        "weight": 700,
        "gradientTo": "#A855F7",
        "marginLeft": 0,
        "solidColor": "#FFFFFF",
        "marginRight": 3,
        "useGradient": false,
        "gradientFrom": "#FFFFFF",
        "gradientAngle": 135,
        "verticalOffset": -1
    },
    intentConfig: {
        "size": 72,
        "weight": 700,
        "gradientTo": "#FFFFFF",
        "marginLeft": 0,
        "solidColor": "#A855F7",
        "marginRight": 0,
        "useGradient": false,
        "gradientFrom": "#A855F7",
        "gradientAngle": 135,
        "verticalOffset": 1
    },
    streakConfig: {
        "length": 366,
        "leftThick": 4,
        "gradientTo": "#7878dd",
        "marginLeft": 0,
        "rightThick": 1,
        "solidColor": "#A855F7",
        "marginRight": 0,
        "useGradient": true,
        "gradientFrom": "#A855F7",
        "gradientAngle": 90
    },
    taglineConfig: {
        "size": 29,
        "weight": 400,
        "marginTop": 5,
        "gradientTo": "#A855F7",
        "marginLeft": 5,
        "solidColor": "#FFFFFF",
        "marginRight": 0,
        "useGradient": false,
        "gradientFrom": "#FFFFFF",
        "gradientAngle": 135
    },
  },
};

// ============================================
// ROUTE-TO-THEME MAPPINGS
// ============================================
export const routeThemeMappings: RouteThemeMapping[] = [
  { route: '/', themeId: '38aafcee-1959-4968-b74b-6c2d53815323' },
];

// ============================================
// ALL PUBLISHED THEMES
// ============================================
export const publishedThemes: Record<string, ThemeConfig> = {
  'luxury-gold': activeTheme,
};

// ============================================
// HELPER FUNCTIONS
// ============================================

export function getThemeForRoute(pathname: string): ThemeConfig {
  const topLevel = '/' + (pathname.split('/')[1] || '');
  const mapping = routeThemeMappings.find(m => m.route === topLevel);
  if (mapping && publishedThemes[mapping.themeId]) {
    return publishedThemes[mapping.themeId];
  }
  return activeTheme;
}

export function applyThemeToRoot(theme: ThemeConfig): void {
  const root = document.documentElement;
  Object.entries(theme.staticColors).forEach(([key, value]) => {
    const cssVar = key.replace(/([A-Z])/g, '-$1').toLowerCase();
    root.style.setProperty(`--${cssVar}`, value);
  });
  root.style.setProperty('--accent', theme.accentConfig.accent);
  root.style.setProperty('--accent-hover', theme.accentConfig.accentHover);
  root.style.setProperty('--accent-glow', theme.accentConfig.accentGlow);
  root.style.setProperty('--accent-foreground', theme.accentConfig.accentForeground);
  root.style.setProperty('--gradient-hero', theme.gradientConfigs.hero);
  root.style.setProperty('--gradient-cta', theme.gradientConfigs.cta);
  root.style.setProperty('--gradient-text', theme.gradientConfigs.text);
}
