/**
 * @fileoverview Supabase Client Configuration
 * @description SSG-safe Supabase client initialization with browser detection.
 *              Auto-generated file - manual edits may be overwritten.
 * 
 * @module integrations/supabase/client
 * @see {@link https://docs.lovable.dev} Lovable Documentation
 * 
 * @brd-reference BRD v33.0 Section 13 - Supabase Integration
 * @brd-reference BRD v33.0 Section 17.2 - SSG Hydration Safety
 * 
 * @example
 * import { supabase } from "@/integrations/supabase/client";
 * 
 * const { data, error } = await supabase
 *   .from('table')
 *   .select('*');
 */

// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

/**
 * Supabase project URL
 * Injected at build time via vite.config.ts define - no values in source code.
 * Set SUPABASE_URL in Vercel platform env.
 * @constant {string}
 */
declare const __SUPABASE_URL__: string;
const SUPABASE_URL = __SUPABASE_URL__;

/**
 * Supabase anon/public key
 * Injected at build time via vite.config.ts define - no values in source code.
 * Set SUPABASE_PUBLISHABLE_KEY in Vercel platform env.
 * @constant {string}
 */
declare const __SUPABASE_ANON_KEY__: string;
const SUPABASE_PUBLISHABLE_KEY = __SUPABASE_ANON_KEY__;

/**
 * SSR-safe browser detection
 * localStorage doesn't exist during SSR, so we check for window
 * @constant {boolean}
 */
const isBrowser = typeof window !== 'undefined';

/**
 * Supabase client instance
 * 
 * Configured with SSG-safe auth settings:
 * - storage: localStorage only in browser (undefined during SSR)
 * - persistSession: only in browser
 * - autoRefreshToken: only in browser
 * - detectSessionInUrl: only in browser
 * 
 * @constant {SupabaseClient<Database>}
 */
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: isBrowser ? localStorage : undefined,
    persistSession: isBrowser,
    autoRefreshToken: isBrowser,
    detectSessionInUrl: isBrowser,
  }
});
